version: '3'
services:
  mongo:
    container_name: "mouse-blog-mongo"
    environment:
      - "TZ=Asia/Bangkok"
    image: mongo:3.6
#    volumes:
#      - ./data/db:/data/db
    ports:
      - 27017:27017
  web:
    image: node:8.9.4
    container_name: "mouse-blog-web"
    environment:
      - "TZ=Asia/Bangkok"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./:/var/www/html/mouse-blog
    working_dir: /var/www/html/mouse-blog
    command: >
      bash -c "npm install && npm start"
  nginx:
    image: nginx:1.13.8
    container_name: "mouse-blog-nginx"
    links:
      - web
    depends_on:
      - web
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl/local/:/var/ssl/local
    ports:
      - 80:80
      - 443:443
